[package]
name = "prtgc_httpadvanced"
version = "0.1.0"
edition = "2021"

[profile.release]
#lto = true
lto = "fat"
codegen-units = 1
debuginfo = 2
opt-level = 3

[dependencies]
reqwest = { version = "*", features = ["blocking", "json"] }
clap = "*"
